version: "2"
services:
  node:
    image: "node"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    command: "npm start"
    container_name: node
  redis:
      image: "redis"
      ports:
        - "6379:6379"
      container_name: redis